// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VissSoft.Infrastracture.Data;

#nullable disable

namespace VissSoft.Infrastracture.Migrations
{
    [DbContext(typeof(VissSoftDbContext))]
    [Migration("20231205091756_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VissSoft.Core.Entities.Course", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("imgLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("course", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            color = "#ffb74a",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(2993),
                            imgLink = "course-1.png",
                            name = "Khai giảng khóa lớp 1",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            color = "#00bc51",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3014),
                            imgLink = "course-2.png",
                            name = "Khai giảng khóa lớp 2",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            color = "#ff9679",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3016),
                            imgLink = "course-1.png",
                            name = "Khai giảng khóa lớp 3",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            color = "#1dc2da",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3017),
                            imgLink = "course-2.png",
                            name = "Khai giảng khóa lớp 4",
                            status = true
                        });
                });

            modelBuilder.Entity("VissSoft.Core.Entities.Intro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("intro", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            content = "Tại lớp học, các thầy cô luôn có những phương pháp giảng dạy để truyền ngọn lửa đam mê môn học cho các con, giúp khơi gợi niềm say mê học tập.",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3135),
                            status = true,
                            title = "Toán học SkyMath"
                        });
                });

            modelBuilder.Entity("VissSoft.Core.Entities.NewAndEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("imgLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("newAndEvent", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            content = "Mọi thông tin về vòng thi sắp tới đây đều được cập nhật và thông báo tại đây",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3148),
                            imgLink = "news-1.png",
                            status = true,
                            title = "Mở vòng thi số 02 Violympic môn Toán bằng Tiếng Anh"
                        },
                        new
                        {
                            id = 2,
                            content = "Mọi thông tin về vòng thi sắp tới đây đều được cập nhật và thông báo tại đây",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3150),
                            imgLink = "news-2.png",
                            status = true,
                            title = "Mở vòng thi số 02 Violympic môn Toán bằng Tiếng Anh"
                        },
                        new
                        {
                            id = 3,
                            content = "Mọi thông tin về vòng thi sắp tới đây đều được cập nhật và thông báo tại đây",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3151),
                            imgLink = "news-3.png",
                            status = true,
                            title = "Mở vòng thi số 02 Violympic môn Toán bằng Tiếng Anh"
                        },
                        new
                        {
                            id = 4,
                            content = "Mọi thông tin về vòng thi sắp tới đây đều được cập nhật và thông báo tại đây",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3152),
                            imgLink = "news-4.png",
                            status = true,
                            title = "Mở vòng thi số 02 Violympic môn Toán bằng Tiếng Anh"
                        });
                });

            modelBuilder.Entity("VissSoft.Core.Entities.Slide", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("imgLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("slogan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("slide", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3169),
                            imgLink = "heroes-1.png",
                            slogan = "Cùng SkyMath bứt phá Điểm 10 không khó",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3170),
                            imgLink = "heroes-2.png",
                            slogan = "Cùng SkyMath bứt phá Điểm 10 không khó",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3171),
                            imgLink = "heroes-3.png",
                            slogan = "Cùng SkyMath bứt phá Điểm 10 không khó",
                            status = true
                        });
                });

            modelBuilder.Entity("VissSoft.Core.Entities.Teacher", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("id");

                    b.ToTable("teacher", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            avatar = "teacher-1.png",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3182),
                            description = "Với kinh nghiệm nhiều năm trong nghề, thầy đã không chỉ giup các em học sinh trở nên yêu thích môn Toán, mà còn đạt giải cao trong các cuộc thi lớn...",
                            name = "Thầy Nguyễn Duy Minh",
                            status = true
                        },
                        new
                        {
                            id = 2,
                            avatar = "teacher-2.png",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3183),
                            description = "Với kinh nghiệm nhiều năm trong nghề, thầy đã không chỉ giup các em học sinh trở nên yêu thích môn Toán, mà còn đạt giải cao trong các cuộc thi lớn...",
                            name = "Cô Hoàng Thị Cẩm Tú",
                            status = true
                        },
                        new
                        {
                            id = 3,
                            avatar = "teacher-3.png",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3184),
                            description = "Với kinh nghiệm nhiều năm trong nghề, thầy đã không chỉ giup các em học sinh trở nên yêu thích môn Toán, mà còn đạt giải cao trong các cuộc thi lớn...",
                            name = "Cô Lương Thùy Linh",
                            status = true
                        },
                        new
                        {
                            id = 4,
                            avatar = "teacher-4.png",
                            created_at = new DateTime(2023, 12, 5, 16, 17, 56, 684, DateTimeKind.Local).AddTicks(3186),
                            description = "Với kinh nghiệm nhiều năm trong nghề, thầy đã không chỉ giup các em học sinh trở nên yêu thích môn Toán, mà còn đạt giải cao trong các cuộc thi lớn...",
                            name = "Cô Trần Mai Phương",
                            status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
